services:
  - type: web
    name: micropile-design-calculator
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT
